import 'package:flutter/material.dart';
import 'package:start_and_earn/components/colors.dart';
const sizeHeight20 = SizedBox(height: 20,);
const sizeHeight15 = SizedBox(height: 15,);
const sizeHeight10 = SizedBox(height: 10,);
const sizeHeight30 = SizedBox(height: 30,);
const sizeHeight40 = SizedBox(height: 40,);
const sizeHeight50 = SizedBox(height: 50,);
const sizeHeight60 = SizedBox(height: 60,);
const sizeHeight70 = SizedBox(height: 70,);
const sizeHeight80 = SizedBox(height: 80,);
const sizeWidth20 = SizedBox(width: 20,);
const sizeWidth10 = SizedBox(width: 10,);
// const dividerWhite = Divider(color: textColor,);
final divider = Divider(color: otherColor,);
const spacer = Spacer();
const kPaddingHorizontal20 = EdgeInsets.symmetric(horizontal: 20);
final kBorderRadius20 = BorderRadius.circular(20);
final kBorderRadius10 = BorderRadius.circular(10);